### ISSUE TITLE
Generating the iOS app. Error: unable to read property list from file Info.plist: The operation couldn’t be completed

### ISSUE THREAD

**Issue by adavidgit11** [OutSystems/cordova-outsystems-payments#45]
Hello,

I'm facing an issue generating the Payments Plugin - Demo from outsystems forge component in iOS with the latest MABS 10. Could you please help me how to solve this error. Thanks in advance

Best regards

Here is the iOSBuildLog

[2024-05-14T08:20:22.519Z] [VERBOSE] [Build] error: unable to read property list from file: source/platforms/ios/Payments Plugin - Demo/Payments Plugin - Demo-Info.plist: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 2.) (in target 'Payments Plugin - Demo' from project 'Payments Plugin - Demo')
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build] CodeSign /Users/sandbox02/Library/Developer/Xcode/DerivedData/Payments_Plugin_-_Demo-blrolmtlinlitjhdlxbbcbvbodfe/Build/Intermediates.noindex/ArchiveIntermediates/Payments\ Plugin\ -\ Demo/InstallationBuildProductsLocation/Applications/Payments\ Plugin\ -\ Demo.app/Frameworks/OSMobileCore.framework (in target 'Payments Plugin - Demo' from project 'Payments Plugin - Demo')
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build]     cd source/platforms/ios
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build]     
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build]     Signing Identity:     "******************************"
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build]     Provisioning Profile: "Payment Plugin Demo"
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build]                           (*****************************)
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build]     
[2024-05-14T08:20:22.519Z] [VERBOSE] [Build]     /usr/bin/codesign --force --sign 67BD42A7E407CEEFA3E6CDFE0EDF287A0833DB3C --options runtime --keychain keys/keychain.keychain-db --preserve-metadata\=identifier,entitlements,flags --generate-entitlement-der /Users/sandbox02/Library/Developer/Xcode/DerivedData/Payments_Plugin_-_Demo-blrolmtlinlitjhdlxbbcbvbodfe/Build/Intermediates.noindex/ArchiveIntermediates/Payments\ Plugin\ -\ Demo/InstallationBuildProductsLocation/Applications/Payments\ Plugin\ -\ Demo.app/Frameworks/OSMobileCore.framework
[2024-05-14T08:20:22.536Z] [VERBOSE] [Build] source/platforms/ios/CordovaLib/CordovaLib.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'CordovaLib' from project 'CordovaLib')
[2024-05-14T08:20:22.536Z] [VERBOSE] [Build] source/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'YapDatabase' from project 'Pods')
[2024-05-14T08:20:22.536Z] [VERBOSE] [Build] source/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'FLEX' from project 'Pods')
[2024-05-14T08:20:22.537Z] [VERBOSE] [Build] ** ARCHIVE FAILED **
[2024-05-14T08:20:22.537Z] [VERBOSE] [Build] The following build commands failed:
[2024-05-14T08:20:22.537Z] [VERBOSE] [Build] 	ProcessInfoPlistFile /Users/sandbox02/Library/Developer/Xcode/DerivedData/Payments_Plugin_-_Demo-blrolmtlinlitjhdlxbbcbvbodfe/Build/Intermediates.noindex/ArchiveIntermediates/Payments\ Plugin\ -\ Demo/InstallationBuildProductsLocation/Applications/Payments\ Plugin\ -\ Demo.app/Info.plist source/platforms/ios/Payments\ Plugin\ -\ Demo/Payments\ Plugin\ -\ Demo-Info.plist (in target 'Payments Plugin - Demo' from project 'Payments Plugin - Demo')
[2024-05-14T08:20:22.537Z] [VERBOSE] [Build] (1 failure)
[2024-05-14T08:20:22.567Z] [VERBOSE] [Build] Command failed with exit code 65: xcodebuild -workspace Payments Plugin - Demo.xcworkspace -scheme Payments Plugin - Demo -configuration Debug -destination generic/platform=iOS -archivePath Payments Plugin - Demo.xcarchive archive OTHER_CODE_SIGN_FLAGS=--options runtime --keychain "keys/keychain.keychain-db"
[2024-05-14T08:20:22.568Z] [VERBOSE] [Build] Error: Command failed with exit code 65: xcodebuild -workspace Payments Plugin - Demo.xcworkspace -scheme Payments Plugin - Demo -configuration Debug -destination generic/platform=iOS -archivePath Payments Plugin - Demo.xcarchive archive OTHER_CODE_SIGN_FLAGS=--options runtime --keychain "keys/keychain.keychain-db"
[2024-05-14T08:20:22.568Z] [VERBOSE] [Build]     at makeError (source/node_modules/execa/lib/error.js:60:11)
[2024-05-14T08:20:22.568Z] [VERBOSE] [Build]     at handlePromise (source/node_modules/execa/index.js:118:26)
[2024-05-14T08:20:22.568Z] [VERBOSE] [Build]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-14T08:20:24.292Z] [INFO] [Build] Zipping application source code...
[2024-05-14T08:20:30.578Z] [INFO] [Build] Saving package and source files...
[2024-05-14T08:20:30.579Z] [ERROR] [Build] -- v --
[2024-05-14T08:20:30.579Z] [ERROR] [Build] The build phase failed to complete!
[2024-05-14T08:20:30.579Z] [ERROR] [Build] Reason: Couldn't generate your app. If the problem persists, check our documentation for more information.
[2024-05-14T08:20:30.579Z] [ERROR] [Build] Additional information:
[2024-05-14T08:20:30.579Z] [ERROR] [Build] [!] The `Payments Plugin - Demo [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Payments Plugin - Demo/Pods-Payments Plugin - Demo.debug.xcconfig'. This can lead to problems with the CocoaPods installation
[2024-05-14T08:20:30.579Z] [ERROR] [Build] [!] The `Payments Plugin - Demo [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Payments Plugin - Demo/Pods-Payments Plugin - Demo.debug.xcconfig'. This can lead to problems with the CocoaPods installation
[2024-05-14T08:20:30.579Z] [ERROR] [Build] [!] The `Payments Plugin - Demo [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Payments Plugin - Demo/Pods-Payments Plugin - Demo.release.xcconfig'. This can lead to problems with the CocoaPods installation
[2024-05-14T08:20:30.579Z] [ERROR] [Build] [!] The `Payments Plugin - Demo [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Payments Plugin - Demo/Pods-Payments Plugin - Demo.release.xcconfig'. This can lead to problems with the CocoaPods installation
[2024-05-14T08:20:30.579Z] [ERROR] [Build] ** ARCHIVE FAILED **
[2024-05-14T08:20:30.579Z] [ERROR] [Build] The following build commands failed:
[2024-05-14T08:20:30.579Z] [ERROR] [Build] 	ProcessInfoPlistFile /Users/sandbox02/Library/Developer/Xcode/DerivedData/Payments_Plugin_-_Demo-blrolmtlinlitjhdlxbbcbvbodfe/Build/Intermediates.noindex/ArchiveIntermediates/Payments\ Plugin\ -\ Demo/InstallationBuildProductsLocation/Applications/Payments\ Plugin\ -\ Demo.app/Info.plist source/platforms/ios/Payments\ Plugin\ -\ Demo/Payments\ Plugin\ -\ Demo-Info.plist (in target 'Payments Plugin - Demo' from project 'Payments Plugin - Demo')
[2024-05-14T08:20:30.579Z] [ERROR] [Build] (1 failure)
[2024-05-14T08:20:30.579Z] [ERROR] [Build] Command failed with exit code 65: xcodebuild -workspace Payments Plugin - Demo.xcworkspace -scheme Payments Plugin - Demo -configuration Debug -destination generic/platform=iOS -archivePath Payments Plugin - Demo.xcarchive archive OTHER_CODE_SIGN_FLAGS=--options runtime --keychain "keys/keychain.keychain-db"
[2024-05-14T08:20:30.579Z] [ERROR] [Build] -- ^ --
[2024-05-14T08:20:30.579Z] [INFO] [Build] Application was not successfully generated!
[2024-05-14T08:20:34.434Z] [INFO] [Build] Execution time: 110806 ms

**Comment by adavidgit11** [comment]
Hi All,

I am now able to generate the ios app by doing the steps below

1. Removing and adding the PaymentsPlugin in the dependencies
2. Untick and tick some of the Apple Pay Configurations in the PaymentsConfigurator screen

Best regards

**Comment by adavidgit11** [comment]
Hi All,

I am now able to generate the ios app by doing the steps below

1. Removing and adding the PaymentsPlugin in the dependencies
2. Untick and tick some of the Apple Pay Configurations in the PaymentsConfigurator screen

Best regards
